In [2]:
print("hello world")


hello world


In [3]:
import numpy as np
num_array = np.array([1, 2, 3, 4, 5])
print(num_array)


[1 2 3 4 5]


In [ ]:
# create an array of zeros
zero_array = np.zeros(
    shape=(3, 4),  # shape of the array (3 rows, 4 columns)
    dtype=np.int32,  # data type of the array elements (32-bit integer)
    order='C'  # memory layout order (C-style row-major order)
)
print(zero_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
