In [3]:
import numpy as np
slc_array = np.array(
   [[2,3,4,5],
    [3,4,6,8],
    [4,5,7,9],
    [5,6,8,10]]
)
print (slc_array[2:4,1:3 ])

[[5 7]
 [6 8]]


In [4]:
import numpy as np
slc_array = np.array(
   [[2,3,4,5],
    [3,4,6,8],
    [4,5,7,9],
    [5,6,8,10]]
)
print (slc_array[1:4,2:3 ])

[[6]
 [7]
 [8]]


In [5]:
print (slc_array.dtype)
print (slc_array.shape)
print (slc_array.ndim)

int64
(4, 4)
2


In [6]:
zeros= np.zeros(
    shape= (4,4),
    dtype= np.int64,
    )
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
fixed = np.full(
    shape= (5,5),
    fill_value = 10,
    dtype= np.int64,
)
fixed

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])