In [4]:
import numpy as np
slc_array = np.array(
   [[2,3,4,5],
    [3,4,6,8],
    [4,5,7,9],
    [5,6,8,10]]
)
print (slc_array[2:4,1:3 ])

[[5 7]
 [6 8]]


In [5]:
import numpy as np
slc_array = np.array(
   [[2,3,4,5],
    [3,4,6,8],
    [4,5,7,9],
    [5,6,8,10]]
)
print (slc_array[1:4,2:3 ])

[[6]
 [7]
 [8]]


In [6]:
print (slc_array.dtype)
print (slc_array.shape)
print (slc_array.ndim)

int64
(4, 4)
2


In [7]:
zeros= np.zeros(
    shape= (4,4),
    dtype= np.int64,
    )
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
fixed = np.full(
    shape= (5,5),
    fill_value = 10,
    dtype= np.int64,
)
fixed

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
id_matrix  = np.eye( 4)
id_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
seqnce = np.arange( 1, 10, 2)
seqnce

array([1, 3, 5, 7, 9])

In [18]:
license = np.linspace(
    start= 0,
    stop= 11,
    num= 4,
    


)
license
    


array([ 0.        ,  3.66666667,  7.33333333, 11.        ])