In [38]:
import numpy as np
sorting = np.array( [3,4,6,7,1,2,5,8,9,10])
sorting.sort()
print(sorting)
# sorting.reshape((2,5))
# sorting = sorting.reshape((2,5))
# print(sorting)



[ 1  2  3  4  5  6  7  8  9 10]


In [37]:
reversed = np.array(
    [54,45,23,12,34,56,78,90,11,22]


)
rvrst = np.flip(reversed)
print(rvrst)

[22 11 90 78 56 34 12 23 45 54]


In [39]:
reverser_array = np.array([3,4,2,3,4,5,6,78,2]
)
reverser_array.sort()
reverser_sort_array = reverser_array[::-1]
print(reverser_sort_array)

[78  6  5  4  4  3  3  2  2]
